// One-shot generator for `src/agents/base.ts` — the harness-neutral polis floor.
// It extracts the `{name}`-parameterized memory protocol (the genus block every
// agent's SOUL carries) from the canonical `ideas/memory.md` cell's `## Protocol`
// section, so the floor has ONE home (the cell) and base.ts is its projection —
// never a hand-copied drift. `founderBase` is `{ ...base }` (founders carry their
// founder-genus via their provenance fragment, not a separate selection organ in
// the current selection-vector form).
//
// Run: `tsx src/toolkit/make-base.ts` (writes src/agents/base.ts).

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const anatomyRoot = join(here, '..', '..');

/** The `## <heading>` section body of a cell, blank-trimmed (mirrors section_body). */
function sectionBody(body: string, heading: string): string {
  const lines = body.split('\n');
  const want = `## ${heading}`.toLowerCase();
  const out: string[] = [];
  let inSection = false;
  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (inSection) {
        break;
      }
      if (line.toLowerCase() === want) {
        inSection = true;
      }
      continue;
    }
    if (inSection) {
      out.push(line);
    }
  }
  while (out.length && out[0]?.trim() === '') {
    out.shift();
  }
  while (out.length && out[out.length - 1]?.trim() === '') {
    out.pop();
  }
  return out.join('\n');
}

function backtick(s: string): string {
  return `\`${s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\``;
}

const memoryRaw = readFileSync(join(anatomyRoot, 'ideas', 'memory.md'), 'utf8');
const memoryBody = memoryRaw.split('---').slice(2).join('---');
const protocol = sectionBody(memoryBody, 'Protocol');

const out = `// The harness-neutral polis floor every agent-anatomy agent spreads (\`{ ...base, … }\`).
// GENERATED by src/toolkit/make-base.ts from ideas/memory.md \`## Protocol\` — do
// not hand-edit; the memory cell is the one home, this is its projection.
//
// In the current selection-vector form every agent lists ALL organs explicitly,
// so \`base\`'s organ contribution is empty; its load-bearing content is the
// \`memoryProtocol\` (the genus block the projector appends as \`## Memory Protocol\`).
// \`founderBase\` is \`{ ...base }\` — founder-genus rides each founder's provenance
// fragment (e.g. \`founder-genus, principal-ic intrinsic\`), not a separate organ.

/** The \`{name}\`-parameterized memory protocol — the genus block, one home. */
export const memoryProtocol = ${backtick(protocol)};

/** The polis-universal floor: the genus content every agent spreads. */
export const base = {
  memoryProtocol,
} as const;

/** The founder floor: base + founder genus (carried via provenance, so \`= base\`). */
export const founderBase = {
  ...base,
} as const;
`;

const dest = join(anatomyRoot, 'src', 'agents', 'base.ts');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out);
process.stdout.write(`wrote ${dest}\n`);
