// The projection-OWNED organ set + their organ-level human glosses — the single
// home for "which organ READMEs are `project-human` output (not hand-authored)".
//
// An organ in `PROJECTED_ORGANS` has its `organs/<organ>/README.md` regenerated by
// `project-human-cli.ts` and byte-locked by `test/projection-boundary.test.ts`: a
// hand-edit diverges from re-projection and fails the gate. `ORGAN_DOCS[<organ>]`
// supplies that organ's `σ*_human` gloss (composed above the value list).
//
// canon-conformance S5 grew this to the full 24-organ set (every organ README is now
// `project-human` output; each organ's hand-authored gloss relocated into its OrganDoc
// here). `test/projection-boundary.test.ts` requires an OrganDoc for every projected organ.

import type { Organ, OrganDoc } from '@leclabs/agent-forge/anatomy';

/** Organs whose committed README is `project-human` output (byte-locked) — all 24. */
export const PROJECTED_ORGANS: readonly Organ[] = [
  'autonomy',
  'persona',
  'role',
  'formality',
  'audience-adaptation',
  'transparency',
  'provenance',
  'objective',
  'guardrails',
  'engineering-principles',
  'heuristics',
  'capabilities',
  'learning',
  'situation-awareness',
  'actions',
  'modalities',
  'model',
  'memory',
  'trigger',
  'framing',
  'reasoning-strategy',
  'satisficing',
  'output-format',
  'self-evaluation',
];

/** The organ-level human gloss (`σ*_human` of the organ concept) per projected organ. */
export const ORGAN_DOCS: Partial<Record<Organ, OrganDoc>> = {
  autonomy: {
    organ: 'autonomy',
    gloss:
      "how much oversight the human keeps during execution — who owns the next decision, and whether an agent must stop and ask before acting. Not how it sounds (that is `persona`/`formality`) nor what it surfaces (that is `transparency`), but the agent's standing permission to proceed: the industry supervision ladder of human in, on, or out of the loop. An agent holds exactly one rung as its default footing, and a narrower instruction can override it for a turn.",
  },
  persona: {
    organ: 'persona',
    gloss:
      'the stable character an agent projects — its voice, register, name, and the "who" a reader infers from it before it does anything. It is a design-time, internal property, fixed when the agent is authored rather than tuned per turn: how an agent sounds and who it is, distinct from `role` (what it is for) and from the CONATUS organs (what it is inclined to do). The catalog is the twelve Jungian brand archetypes — the canonical character priors an agent can adopt.',
  },
  role: {
    organ: 'role',
    gloss:
      "the self-declared scope of office — what an agent claims to be for and, by omission, what it disclaims. In the language of org and law it is the agent's remit or charter of office: the boundary it presents as its own, each remit folding in its own disclaimer of what is someone else's office. It is distinct from the goal an agent pursues (`objective`) and the limits it obeys (`guardrails`); the mandates are deliberately disjoint, so any task lands in exactly one office's remit.",
  },
  formality: {
    organ: 'formality',
    gloss:
      "an agent's standing manner — the tone and bearing it keeps across every turn, independent of any particular task: how verbose it is, whether it hedges or commits, how it delivers a verdict, whether it reassures. Where `persona` is the character an agent projects and `audience-adaptation` is how it tunes to one interlocutor in the moment, formality is the habitual set of presentation — how an agent sounds by habit, the STANCE-side twin of `heuristics` (how it moves by habit). It is built from a single dense genus register that every agent shares, plus role specializations that each conjoin extra discipline on top.",
  },
  'audience-adaptation': {
    organ: 'audience-adaptation',
    gloss:
      'the per-turn, internal modulation of presentation to this interlocutor and this moment — formality, density, length, mirroring; how an agent tunes its face to the room. It is distinct from `formality`, the standing manner that holds across every turn regardless of audience: audience-adaptation adapts turn-to-turn, formality persists. It governs only how a reply is dressed — not what it claims, refuses, or surfaces — answering one question each turn: who is reading this, and how should I pitch it to them? Every value shares one backbone — match density, mirror notation, escalate precision over length — and differs in which reader it targets.',
  },
  transparency: {
    organ: 'transparency',
    gloss:
      'the face an agent turns outward right now — how much of its own reasoning, evidence, and uncertainty it makes legible to whoever reads its output: shown derivation, citations, confidence hedges, uncertainty flags, an honest "I don\'t know." It is deliberately split from `reasoning-strategy`, the same reasoning trace used to choose rather than shown to the reader — reasoning-strategy is the thinking, transparency is the showing. The values form a spectrum from emitting the bare conclusion to exposing the full derivation, plus orthogonal duties to attribute provenance and to flag what is uncertain or unchecked.',
  },
  provenance: {
    organ: 'provenance',
    gloss:
      'the legible mark of an agent\'s identity to the outside world — how it is recognized from without: its archetypal lineage, the named ancestor form it regenerates from, and the standing that descent confers. It answers "where did this agent come from, and by what authority does it speak?" — distinct from `model`, the machinery that actually runs it: provenance is what marks the agent, model is what runs it. Each lineage carries an emblem (a glyph and color) and a standing — whether the agent holds mission-command authority intrinsically or is a downstream delegate.',
  },
  objective: {
    organ: 'objective',
    gloss:
      'the objective an agent is built to pursue — the design-time, internal drive that orients every action it takes. It is not the office an agent presents (that is `role`) but the goal it actually pursues: the operative success-criterion, the thing against which the agent silently scores itself, the answer to "what does this agent ultimately want?" Each value is one north-star stated with a built-in acceptance gate — a reusable palette of drives (correctness, delivery, safety, thoroughness, and the rest) rather than a goal bespoke to any one agent.',
  },
  guardrails: {
    organ: 'guardrails',
    gloss:
      'the set of inviolable constraints on action — what an agent will not do, by construction. Where `role` declares the office an agent claims and `objective` names the goal it pursues, guardrails are the hard limits it obeys: the prohibitions, refusal lines, and bias-toward-safety baked in at design time rather than chosen per turn. They are negative and load-bearing — an agent that violates its guardrails has malfunctioned, not merely chosen poorly. The canonical core is HHH (helpfulness, honesty, harm-avoidance), extended for an agent that acts by oversight, scope, privacy, accountability, and an untrusted-input posture; an agent holds a subset, and more constraints mean a more tightly bounded agent.',
  },
  'engineering-principles': {
    organ: 'engineering-principles',
    gloss:
      'the standing engineering directives an agent operates by — its deliberate working methodology, how it is told to work. Distinct from `guardrails` (its constitution and safety limits) and `heuristics` (its cognitive shortcuts), this organ is the methodology itself: DRY, first-principles, MECE, separation-of-concerns, trust-but-verify, and the rest. Each directive leads with the positive move — what to do — and an agent holds whichever set it works by.',
  },
  heuristics: {
    organ: 'heuristics',
    gloss:
      'the standing move-biases an agent reaches for under bounded time and information — Gigerenzer fast-and-frugal decision rules, not hard prohibitions (that is `guardrails`) nor a manner of speech (that is `formality`). An agent composites a SET of them, and that set is part of what makes one agent move differently from another faced with the same task.',
  },
  capabilities: {
    organ: 'capabilities',
    gloss:
      'the consolidated skills and know-how an agent carries between turns — the repertoire of what it can enact. Where `guardrails` say what an agent may do and `objective` says what it wants, capabilities say what it is actually able to do: the durable craft it brings independent of any single task. Each value is one generalized skill area — software-engineering, system-design, verification-testing, technical-writing, and the like — a coherent bundle of methods and disciplines that travels with whichever agents hold it, additive and shared rather than restated per agent.',
  },
  learning: {
    organ: 'learning',
    gloss:
      "an agent's durable, identity-level learning — the preferences, lessons, and self-model that bias future action across sessions. Where `capabilities` is the repertoire of what an agent can do, learning is who it has become: the consolidated residue of experience that changes how it acts next time, by default, without being told again. The dimension it governs is the learning mode over time — how, and whether, lessons persist and reshape behavior between sessions — running from no persistence at all (static-frozen) to continuous live adaptation (continual-online); an agent's binding declares which regime it runs under.",
  },
  'situation-awareness': {
    organ: 'situation-awareness',
    gloss:
      "an agent's resident hold of the construed semantic whole across a task — the single coherent picture of what the whole job is, kept in mind from the first turn to the last. It is the standing counterpart to `framing`: where framing forms a fresh interpretation this turn, situation-awareness keeps that frame resident and refuses to let the latest fragment overwrite it. Every value has the same two-part shape — hold the relevant whole resident, and anchor each local act back to it, never collapsing to the fragment loudest right now — differing only in which whole a given role must hold (a reviewer's data-flow and trust-boundaries, a planner's goal-and-frame, a tester's correctness surface).",
  },
  actions: {
    organ: 'actions',
    gloss:
      "an agent's hands — the standing set of actuators it can invoke to change or observe the world: read a source, call a tool, run code, edit a file, drive a GUI, dispatch a subagent, send a message, command hardware. Where `modalities` are the channels by which the world enters an agent (its eyes), actions are what it reaches out and does — the apparatus side of `capabilities`, the concrete instruments through which know-how lands as change. Each value is one canonical effector carved by the kind of actuation it performs; an agent holds them as a set, its reach is exactly the union of the actions it holds, and not holding an effector is a real boundary.",
  },
  modalities: {
    organ: 'modalities',
    gloss:
      "the channels by which the world enters an agent — the percept-sources it reads: operator directives, tool results, diffs, codebases, corpora, retrieved documents, each holder's specialized eyes onto its domain. They are the mirror of `actions`, the agent's hands: actions change the world, modalities take it in. Each value binds one named percept-source scoped to its holder's work (the investigator senses defect reports and logs, the writer senses ADRs and docs); an agent composites a scoped bundle — the near-universal operator-directive and tool-result channels plus a domain eye — and the sensor is what opens the cycle its framing and reasoning work on.",
  },
  model: {
    organ: 'model',
    gloss:
      "the inference engine and runtime that actually executes an agent — the model weights, the harness, and the loop; in industry terms the body the agent runs on. It is deliberately an accident, not the agent's substance: which model and harness run an agent can change, yet the agent persists as the same individual across the swap because its identity is anchored in its archetype and memory-stack, not in the body executing it. Compare its STANCE-side twin `provenance` — identity as recognized from outside — versus model, identity as the machinery that acts: model is what runs the agent, not what the agent is.",
  },
  memory: {
    organ: 'memory',
    gloss:
      "the external store an agent reads and writes to persist state across turns and sessions — its written record: scratchpad files, a vector store, a database, a memory home, anything written this turn to be read back next turn or next session. Where the model's context window is volatile and forgotten at session end, memory is what survives the boundary. It is distinct from the apparatus that uses it — not the `actions` that change the world nor the `modalities` through which the world enters — but the durable record those acts leave behind and draw upon.",
  },
  trigger: {
    organ: 'trigger',
    gloss:
      'the concrete input as taken up this turn — the single parsed observation that arrives at the top of one act of the agent loop and gets read as "here is what I am being handed this turn." Where `modalities` is the standing channel by which the world can enter, a trigger is the one thing that did enter now, already construed into the shape the agent reads: not raw bytes and not yet an interpretation, but the opening of the turn. The values partition the turn-opening input space — a user message, a tool result, a peer agent\'s message, an environment event, a scheduled fire, an introspection request — every turn opening on exactly one.',
  },
  framing: {
    organ: 'framing',
    gloss:
      'the working interpretation an agent forms of its input — the problem framing it adopts before it reasons or acts. Faced with the same trigger, one agent sees a defect to explain, another a goal to decompose, another a data-flow to check: the input is one, the framing differs by who is looking. It is per-turn and internal, formed fresh each cycle and never emitted, and it precedes `reasoning-strategy` — first the agent decides what kind of problem this is, then reasons within that frame. Each value is one lens (analytical, diagnostic, risk-oriented, first-principles, and the rest), and the framing an agent binds is its characteristic question — the per-turn root of its specialization.',
  },
  'reasoning-strategy': {
    organ: 'reasoning-strategy',
    gloss:
      'the in-context reasoning that weighs options — planning, chain-of-thought, search over next moves — taken as the act of choosing itself, not as something shown. It is the mental work an agent does after it has framed the situation (`framing`) and before it commits to a course (`satisficing`): decomposing the problem, generating candidates, testing them against constraints, converging on the move worth making. It is the CONATUS-side twin of `transparency` — the same trace, split by whether it is used to choose or presented to an audience — and, unlike a shared-voice organ, has no common genus: each role holds exactly one value that is the method of inquiry its work demands.',
  },
  satisficing: {
    organ: 'satisficing',
    gloss:
      'the commitment to one course — the moment that closes `reasoning-strategy` and selects the action to enact. Reasoning-strategy weighs the options; satisficing commits to one: the decisive cut between thinking and doing, fixing on exactly one candidate move and handing it to `output-format`. Each value is the specific commitment a given kind of agent makes — a maker commits to a design, an implementer to a diff, an investigator to a cause (or honestly to not knowing), a tester to a set of checks — always the same shape, close the search and fix on one thing, but tailored to the craft, some carrying an honest "cannot resolve" verdict.',
  },
  'output-format': {
    organ: 'output-format',
    gloss:
      "an agent's emitted action — the single thing it actually puts into the world this turn: the tool call or token stream emitted after the turn's trigger is taken up, construed, deliberated, and resolved. It is the only organ that leaves the agent and reaches reality; everything upstream is internal preparation, and `self-evaluation` downstream reads the result. Where `capabilities` says what an agent can do and `satisficing` is the commitment to one course, output-format is the doing itself — the move made flesh as an artifact, carved by the form of the thing emitted (prose, code, a document, a structured payload, a bounded verdict, a visual, or a side effect).",
  },
  'self-evaluation': {
    organ: 'self-evaluation',
    gloss:
      "the reading of the result against intent — did the work succeed, self-critique it, and emit the error signal that feeds the next cycle. It is the closing beat of one turn of doing: after an agent forms a `framing`, deliberates, `satisficing`s, and enacts via `output-format`, self-evaluation looks back at what came out and grades it — the gate deciding whether the result is good enough to stand or whether the error loops back into the next move (and, when durable, into `learning`). Every value shares one shape — run a check against a held standard, self-critique, feed the error back — differing only in what oracle decides the verdict: an executable ground truth, a human, a second model, a vote across runs, a written spec, or the agent's own re-reading.",
  },
};
