// The projection-OWNED organ set + their organ-level human glosses — the single
// home for "which organ READMEs are `project-human` output (not hand-authored)".
//
// An organ in `PROJECTED_ORGANS` has its `organs/<organ>/README.md` regenerated by
// `project-human-cli.ts` and byte-locked by `test/projection-boundary.test.ts`: a
// hand-edit diverges from re-projection and fails the gate. `ORGAN_DOCS[<organ>]`
// supplies that organ's `σ*_human` gloss (composed above the value list); an organ
// projected WITHOUT a doc falls back to the default genus line from `ANATOMY`.
//
// E2 seeds this with the one witnessed organ; the canon-conformance S5 slice
// ("regenerate human views") grows the set to the full 24 (moving each organ's
// hand-authored gloss into its `OrganDoc` here, then adding it to PROJECTED_ORGANS).

import type { Organ, OrganDoc } from '@leclabs/agent-forge/anatomy';

/** Organs whose committed README is `project-human` output (byte-locked). */
export const PROJECTED_ORGANS: readonly Organ[] = ['heuristics'];

/** The organ-level human gloss (`σ*_human` of the organ concept) per projected organ. */
export const ORGAN_DOCS: Partial<Record<Organ, OrganDoc>> = {
  heuristics: {
    organ: 'heuristics',
    gloss:
      'the standing move-biases an agent reaches for under bounded time and information — ' +
      'Gigerenzer fast-and-frugal decision rules, not hard prohibitions (that is `guardrails`) ' +
      'nor a manner of speech (that is `formality`). An agent composites a SET of them, and that ' +
      'set is part of what makes one agent move differently from another faced with the same task.',
  },
};
