// The claude projection of a dimension value fragment: render a typed module back to
// its canonical cell-body markdown form.
//
// The skill round-trip machinery (`SkillModule` / `skillToMarkdown`) was retired in
// the forge-anatomy de-braid: a skill no longer stores a verbatim `body`, its sole
// σ* payload is the forge `Skill.formalBlock` and its SKILL.md is generated by the
// forge claude/codex adapter (`skillToClaudeMd`), never round-tripped from a stored
// body. Only the fragment wrap survives (its byte-anchor is the value string
// itself).

/**
 * Render a dimension value to its canonical cell body: `\n\n<value>\n`. A dimension
 * value is a branded string whose content IS the body ⟨α, residue⟩, so this is the
 * identity wrap (no field reconstruction).
 */
export function fragmentToMarkdown(value: string): string {
  return `\n\n${value}\n`;
}
