// project-human gate (E2): `projectHumanOrgan` is a PURE DETERMINISTIC function of
// `(organ, values, doc)`. Proven here over a synthetic fixture — determinism
// (idempotent across runs + input-order-independent via slug sort), the closed
// shape, and the source-only footer. The CORPUS witness (a committed organ README
// that equals its re-projection byte-for-byte) lives in agent-anatomy's
// `test/projection-boundary.test.ts`; this proves the function it depends on.

import { describe, expect, it } from 'vitest';
import {
  type Fragment,
  type OrganDoc,
  projectHumanOrgan,
} from '../../src/anatomy/index.js';

// `heuristics` is a CONATUS/coined/set organ — a stable fixture for the shape.
const values: readonly Fragment[] = [
  {
    organ: 'heuristics',
    slug: 'take-the-best',
    definiens: 'decide on the one best cue.',
  },
  {
    organ: 'heuristics',
    slug: 'anchoring',
    definiens: 'anchor, adjust insufficiently.',
  },
  {
    organ: 'heuristics',
    slug: 'recognition',
    definiens: 'choose the recognized option.',
  },
];

describe('projectHumanOrgan — pure deterministic human-view', () => {
  it('is idempotent (same bytes across repeated projection)', () => {
    const a = projectHumanOrgan('heuristics', values);
    const b = projectHumanOrgan('heuristics', values);
    expect(a).toBe(b);
  });

  it('is input-order-independent (slug-sorted)', () => {
    const forward = projectHumanOrgan('heuristics', values);
    const shuffled = projectHumanOrgan('heuristics', [
      values[2] as Fragment,
      values[0] as Fragment,
      values[1] as Fragment,
    ]);
    expect(shuffled).toBe(forward);
    // The value order in the output is slug-lexicographic, not source order.
    const md = forward;
    const iAnchor = md.indexOf('`anchoring`');
    const iRecog = md.indexOf('`recognition`');
    const iTake = md.indexOf('`take-the-best`');
    expect(iAnchor).toBeLessThan(iRecog);
    expect(iRecog).toBeLessThan(iTake);
  });

  it('emits the closed shape: H1, genus quote, Values, footer', () => {
    const md = projectHumanOrgan('heuristics', values);
    expect(md.startsWith('# heuristics\n')).toBe(true);
    expect(md).toContain(
      '> **Organ — CONATUS · Heuristics** — a coined set organ.',
    );
    expect(md).toContain('## Values');
    expect(md).toContain('- **`anchoring`** ≜ anchor, adjust insufficiently.');
    expect(md).toContain('generated by `project-human`');
    expect(md).toContain('do not hand-edit._');
    expect(md.endsWith('\n')).toBe(true);
  });

  it('an OrganDoc gloss replaces the default genus line', () => {
    const doc: OrganDoc = {
      organ: 'heuristics',
      gloss:
        'the standing move-biases that incline an agent toward some choices.',
    };
    const md = projectHumanOrgan('heuristics', values, doc);
    expect(md).toContain(
      '> **Organ — CONATUS · Heuristics.** the standing move-biases that incline an agent toward some choices.',
    );
    expect(md).not.toContain('— a coined set organ.');
  });
});
