// B4 culture->IR bridge — multi-dialect round-trip gate (koine side).
//
// The mind corpus emits a single canonical koine IR (mind/toolkit/emit_ir.py;
// the committed `mind.koine.json` fixture below is its output: 11 agents +
// 7 skills = the 18 culture artifacts). B4's done-when is that this IR
// compiles to >=2 client dialects ROUND-TRIP CLEAN — `read(write(IR)) == IR`
// (structural identity on the IR, not byte-identity on the dialect file;
// koine normalizes per dialect, so identity lives on the IR waypoint).
//
// CLEAN (full agent+skill support): claude (reference) + codex (TOML). Both
//   must recover agents+skills to structural identity with ZERO warnings.
// LOSSY-BY-DESIGN (the coverage-honesty deliverable): cursor / opencode
//   declare agents partial/none. They MUST skip+warn (koine's "declare support
//   honestly"), never silently corrupt — their supported subset (skills) still
//   round-trips clean. This is asserted, not assumed: the map is executable.
//
// The fixture is regenerated by `cd packages/mind && python3 toolkit/emit_ir.py
// <path> --target claude --target codex`. mind/toolkit/test_ir_bridge.py owns
// the emit-correctness + claude-byte-parity half; this owns the adapter
// round-trip contract.
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { Agent, IR, Skill } from '@leclabs/koine-core';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { claudeAdapter } from '../../src/claude/index.js';
import { codexAdapter } from '../../src/codex/index.js';
import { cursorAdapter } from '../../src/cursor/index.js';
import { opencodeAdapter } from '../../src/opencode/index.js';

const fixture = JSON.parse(
  readFileSync(join(__dirname, 'mind.koine.json'), 'utf8'),
) as { agents: Agent[]; skills: Skill[] };

// The IR under test: mind's emitted agents + skills. (manifest.overrides
// carries the skill `/trigger` affordances — an adapter-output concern, not an
// IR-resource field, so it is not part of the resource round-trip identity.)
function mindIR(targets: string[]): IR {
  return {
    manifest: { koine: 1, scope: 'project', targets },
    agents: fixture.agents,
    skills: fixture.skills,
  };
}

describe('B4 culture->IR bridge: the emitted IR is well-formed', () => {
  it('carries the 18 culture artifacts (11 agents + 7 skills)', () => {
    expect(fixture.agents).toHaveLength(11);
    expect(fixture.skills).toHaveLength(7);
    for (const a of fixture.agents) {
      expect(a.name).toBeTruthy();
      expect(a.body).toBeTruthy();
    }
    for (const s of fixture.skills) {
      expect(s.name).toBeTruthy();
      expect(s.description).toBeTruthy();
      expect(s.body).toBeTruthy();
    }
  });
});

// --- CLEAN dialects: read(write(IR)) == IR, zero warnings -------------------
describe.each([
  { adapter: claudeAdapter, id: 'claude' },
  { adapter: codexAdapter, id: 'codex' },
])('B4 round-trip CLEAN: $id', ({ adapter }) => {
  let cwd: string;
  beforeEach(() => {
    cwd = mkdtempSync(join(tmpdir(), `koine-b4-${adapter.id}-`));
  });
  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true });
  });

  it('declares full agent + skill support', () => {
    expect(adapter.capabilities.resources.agents).toBe('full');
    expect(adapter.capabilities.resources.skills).toBe('full');
  });

  it('IR -> dialect -> IR recovers all 18 artifacts to identity', async () => {
    const ir = mindIR([adapter.id]);
    const report = await adapter.write(ir, 'project', cwd, {});
    const re = await adapter.read('project', cwd);
    // No artifact dropped or downgraded.
    expect(report.warnings).toEqual([]);
    expect(report.skipped).toEqual([]);
    // Structural identity on every agent and every skill.
    expect(re.agents).toEqual(ir.agents);
    expect(re.skills).toEqual(ir.skills);
  });
});

// --- LOSSY-BY-DESIGN: honest skip+warn, supported subset still clean --------
describe.each([
  { adapter: cursorAdapter, id: 'cursor' }, // agents: partial
  { adapter: opencodeAdapter, id: 'opencode' }, // agents: none
])('B4 coverage honesty (lossy-by-design): $id', ({ adapter }) => {
  let cwd: string;
  beforeEach(() => {
    cwd = mkdtempSync(join(tmpdir(), `koine-b4-lossy-${adapter.id}-`));
  });
  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true });
  });

  it('does not claim full agent support', () => {
    expect(adapter.capabilities.resources.agents).not.toBe('full');
  });

  it('skips agents with a warning rather than corrupting them', async () => {
    const ir = mindIR([adapter.id]);
    const report = await adapter.write(ir, 'project', cwd, {});
    const re = await adapter.read('project', cwd);
    // Declared honestly: the 11 agents are skipped + warned, never silently
    // recovered as garbage.
    expect(report.warnings.length).toBeGreaterThan(0);
    expect(report.skipped.length).toBe(ir.agents.length);
    expect(re.agents ?? []).toHaveLength(0);
    // The supported subset (skills) still round-trips clean.
    expect(re.skills).toEqual(ir.skills);
  });
});
