// project-human ≜ the harness-AGNOSTIC half of boundary-projection: render a
// canonical cell to its human-view. The model law
//
//   project-human(c) = ⟨ σ*_human(k) : k ∈ concepts(c) ⟩
//
// A human-view is COMPOSED from the human-signs of the cell's concepts — never
// authored at the boundary. `projectHumanOrgan` realizes it for the ORGAN unit:
// its concepts are the organ itself (σ*_human = the optional `OrganDoc.gloss`) and
// its value cells (σ*_human = each value's `slug ≜ definiens`). The output is a
// PURE DETERMINISTIC function of `(organ, values, doc)` — sort is by slug, meta is
// read from `ANATOMY`, no clock/host/IO — so a committed organ README that diverges
// from re-projection is a hand-edit (the falsifier), catchable by a byte diff.

import { ANATOMY, type Organ } from './index.js';

/**
 * The optional organ-level human gloss — `σ*_human` of the ORGAN concept itself,
 * composed by `projectHumanOrgan` above the value list. Source-owned; when a
 * projected organ has no `OrganDoc`, a default genus line from `ANATOMY` meta
 * stands in its place.
 */
export interface OrganDoc {
  readonly organ: Organ;
  /** One-paragraph human gloss of what this organ is (markdown, no trailing nl). */
  readonly gloss: string;
}

/** `audience-adaptation` → `Audience-Adaptation`, `output-format` → `Output-Format`. */
function organTitle(organ: string): string {
  return organ
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('-');
}

/** Lexicographic order — the deterministic value ordering of a human-view. */
function byBody(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * `project-human` for an organ: compose its value cells into the canonical human
 * README. PURE and DETERMINISTIC in `(organ, values, doc)` — the value list is
 * slug-sorted, the genus line is read from `ANATOMY`, and nothing else enters. The
 * closed shape:
 *
 *   # <organ>
 *
 *   > **Organ — <AXIS> · <Title>.** <doc.gloss | default genus line>
 *
 *   ## Values
 *
 *   - **`<slug>`** ≜ <definiens>
 *   …
 *
 *   ---
 *
 *   _<generated-by footer>_
 *
 * A committed `organs/<organ>/README.md` is projection-owned iff it equals this
 * output byte-for-byte; any hand-edit diverges and the boundary gate fails.
 */
export function projectHumanOrgan(
  organ: Organ,
  values: readonly string[],
  doc?: OrganDoc,
): string {
  const meta = ANATOMY[organ];
  const title = organTitle(organ);
  const sorted = [...values].sort(byBody);

  const lines: string[] = [`# ${organ}`, ''];
  lines.push(
    doc
      ? `> **Organ — ${meta.axis} · ${title}.** ${doc.gloss}`
      : `> **Organ — ${meta.axis} · ${title}** — a ${meta.kind} ${meta.arity} organ.`,
    '',
  );
  lines.push('## Values', '');
  for (const body of sorted) {
    lines.push(`- ${body}`);
  }
  lines.push(
    '',
    '---',
    '',
    `_This file is the human projection of \`organs/${organ}/\` — generated by \`project-human\` from the organ’s canonical semantics (${meta.kind} ${meta.arity} value-catalog). Edit the \`.ts\` value cells and regenerate; do not hand-edit._`,
  );
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}
