// B4 culture->IR bridge — multi-dialect round-trip gate (agent-forge side).
//
// The agent-anatomy corpus emits a single canonical agent-forge IR (agent-anatomy/toolkit/emit_ir.py;
// the committed `agent-anatomy.agent-forge.json` fixture below is its output: 11 agents +
// 10 skills = the 21 culture artifacts). B4's done-when is that this IR
// compiles to >=2 client dialects ROUND-TRIP CLEAN — `read(write(IR)) == IR`
// (structural identity on the IR, not byte-identity on the dialect file;
// agent-forge normalizes per dialect, so identity lives on the IR waypoint).
//
// CLEAN (full agent+skill support): claude (reference) + codex (TOML). Both
//   must recover agents+skills to structural identity with ZERO warnings.
// LOSSY-BY-DESIGN (the coverage-honesty deliverable): cursor / opencode
//   declare agents partial/none. They MUST skip+warn (agent-forge's "declare support
//   honestly"), never silently corrupt — their supported subset (skills) still
//   round-trips clean. This is asserted, not assumed: the map is executable.
//
// The fixture is regenerated by `cd packages/agent-anatomy && python3 toolkit/emit_ir.py
// <path> --target claude --target codex`. agent-anatomy/toolkit/test_ir_bridge.py owns
// the emit-correctness + claude-byte-parity half; this owns the adapter
// round-trip contract.
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { claudeAdapter } from '../../../src/adapters/claude/index.js';
import { codexAdapter } from '../../../src/adapters/codex/index.js';
import { cursorAdapter } from '../../../src/adapters/cursor/index.js';
import { opencodeAdapter } from '../../../src/adapters/opencode/index.js';
import type { Agent, IR, Skill } from '../../../src/core/index.js';

const fixture = JSON.parse(
  readFileSync(join(__dirname, 'agent-anatomy.agent-forge.json'), 'utf8'),
) as { agents: Agent[]; skills: Skill[] };

// The IR under test: agent-anatomy's emitted agents + skills. (manifest.overrides
// carries the skill `/trigger` affordances — an adapter-output concern, not an
// IR-resource field, so it is not part of the resource round-trip identity.)
function anatomyIR(targets: string[]): IR {
  return {
    manifest: { agentForge: 1, scope: 'project', targets },
    agents: fixture.agents,
    skills: fixture.skills,
  };
}

describe('B4 culture->IR bridge: the emitted IR is well-formed', () => {
  it('carries the 21 culture artifacts (11 agents + 10 skills)', () => {
    expect(fixture.agents).toHaveLength(11);
    expect(fixture.skills).toHaveLength(10);
    for (const a of fixture.agents) {
      expect(a.name).toBeTruthy();
      expect(a.body).toBeTruthy();
    }
    for (const s of fixture.skills) {
      expect(s.name).toBeTruthy();
      expect(s.description).toBeTruthy();
      expect(s.body).toBeTruthy();
    }
  });
});

// --- CLEAN dialects: read(write(IR)) == IR, zero warnings -------------------
describe.each([{ adapter: claudeAdapter, id: 'claude' }])(
  'B4 round-trip CLEAN: $id',
  ({ adapter }) => {
    let cwd: string;
    beforeEach(() => {
      cwd = mkdtempSync(join(tmpdir(), `agent-forge-b4-${adapter.id}-`));
    });
    afterEach(() => {
      rmSync(cwd, { recursive: true, force: true });
    });

    it('declares full agent + skill support', () => {
      expect(adapter.capabilities.resources.agents).toBe('full');
      expect(adapter.capabilities.resources.skills).toBe('full');
    });

    it('IR -> dialect -> IR recovers all 21 artifacts to identity', async () => {
      const ir = anatomyIR([adapter.id]);
      const report = await adapter.write(ir, 'project', cwd, {});
      const re = await adapter.read('project', cwd);
      // No artifact dropped or downgraded.
      expect(report.warnings).toEqual([]);
      expect(report.skipped).toEqual([]);
      // Structural identity on every agent and every skill.
      expect(re.agents).toEqual(ir.agents);
      expect(re.skills).toEqual(ir.skills);
    });
  },
);

// --- codex: CLEAN except the undocumented `color` field [CX1] --------------
// codex's agent TOML has no documented color field (agentToCodexTomlObject /
// write.ts drop it with a named warning rather than fabricating one), so the
// agent-anatomy fixture — every agent carries `color` — is not a zero-loss
// round trip here the way it is for claude. Skills are unaffected and still
// recover to identity.
describe('B4 round-trip: codex (color dropped per CX1)', () => {
  let cwd: string;
  beforeEach(() => {
    cwd = mkdtempSync(join(tmpdir(), 'agent-forge-b4-codex-'));
  });
  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true });
  });

  it('declares full agent + skill support', () => {
    expect(codexAdapter.capabilities.resources.agents).toBe('full');
    expect(codexAdapter.capabilities.resources.skills).toBe('full');
  });

  it('IR -> dialect -> IR recovers agents modulo the undocumented `color` field (named-warning drop) + skills to identity', async () => {
    const ir = anatomyIR(['codex']);
    const report = await codexAdapter.write(ir, 'project', cwd, {});
    const re = await codexAdapter.read('project', cwd);
    // No skip — color is a field-level drop, not a whole-resource skip.
    expect(report.skipped).toEqual([]);
    // One named warning per agent (every fixture agent carries color).
    expect(report.warnings).toHaveLength(ir.agents?.length ?? 0);
    expect(report.warnings.every((w) => w.includes('color'))).toBe(true);
    const withoutColor = (ir.agents ?? []).map(
      ({ color: _color, ...rest }) => rest,
    );
    expect(re.agents).toEqual(withoutColor);
    expect(re.skills).toEqual(ir.skills);
  });
});

// --- LOSSY-BY-DESIGN: honest skip+warn, supported subset still clean --------
describe.each([{ adapter: opencodeAdapter, id: 'opencode' }])(
  // agents: none
  'B4 coverage honesty (lossy-by-design): $id',
  ({ adapter }) => {
    let cwd: string;
    beforeEach(() => {
      cwd = mkdtempSync(join(tmpdir(), `agent-forge-b4-lossy-${adapter.id}-`));
    });
    afterEach(() => {
      rmSync(cwd, { recursive: true, force: true });
    });

    it('does not claim full agent support', () => {
      expect(adapter.capabilities.resources.agents).not.toBe('full');
    });

    it('skips agents with a warning rather than corrupting them', async () => {
      const ir = anatomyIR([adapter.id]);
      const report = await adapter.write(ir, 'project', cwd, {});
      const re = await adapter.read('project', cwd);
      // Declared honestly: the 11 agents are skipped + warned, never silently
      // recovered as garbage.
      expect(report.warnings.length).toBeGreaterThan(0);
      expect(report.skipped.length).toBe(ir.agents.length);
      expect(re.agents ?? []).toHaveLength(0);
      // The supported subset (skills) still round-trips clean.
      expect(re.skills).toEqual(ir.skills);
    });
  },
);

// cursor no longer belongs in the lossy-by-design (whole-resource-skip) group
// above: the cursor-adapter-truth fix (E8.S5/E1.S8, [CU3]) lifts
// `.cursor/agents/*.md` for real. Declared support stays 'partial' because
// the documented frontmatter is name/description/model only — same
// field-level-drop shape as codex's `color` (§3 cursor d3/[CU3]).
describe('B4 round-trip: cursor (color dropped per CU3; the mapped subset lifts clean)', () => {
  let cwd: string;
  beforeEach(() => {
    cwd = mkdtempSync(join(tmpdir(), 'agent-forge-b4-cursor-'));
  });
  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true });
  });

  it('declares partial agent support (documented frontmatter: name/description/model only)', () => {
    expect(cursorAdapter.capabilities.resources.agents).toBe('partial');
  });

  it('IR -> dialect -> IR recovers agents modulo the undocumented `color` field (named-warning drop) + skills to identity', async () => {
    const ir = anatomyIR(['cursor']);
    const report = await cursorAdapter.write(ir, 'project', cwd, {});
    const re = await cursorAdapter.read('project', cwd);
    // No skip — color is a field-level drop, not a whole-resource skip [CU3].
    expect(report.skipped).toEqual([]);
    expect(report.warnings.some((w) => w.includes('color'))).toBe(true);
    const withoutColor = (ir.agents ?? []).map(
      ({ color: _color, ...rest }) => rest,
    );
    expect(re.agents).toEqual(withoutColor);
    expect(re.skills).toEqual(ir.skills);
  });
});
