import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dump, load } from 'js-yaml';
import type {
  Agent,
  Command,
  Hook,
  IR,
  Scope,
  WriteOpts,
  WriteReport,
} from '../../core/index.js';
import { canonicalToAmp } from './events.js';
import { paths } from './paths.js';

/**
 * Delivery for agents/commands/hooks: Amp has no file-config surface for any
 * of the three (agents = built-ins + `amp.createAgent()`; commands folded
 * into the Plugin API's `registerCommand`; legacy `amp.hooks` retired for
 * `on()` registrations) — capability `plugin` for all three [AM1][AM2][AM3]
 * [AM9]. Each emitter writes a generated Bun-run `.ts` file (the artifact
 * Amp actually loads) plus a YAML sidecar (our source of truth on re-read,
 * same two-file split as the opencode hooks precedent).
 */

// ---- agents ---------------------------------------------------------------

/** IR agent fields `amp.createAgent()` has no documented parameter for —
 * only `name` + the system prompt (`body`) are mapped [AM1][AM9]; every
 * other field is a named, per-agent drop, never silently fabricated in. */
const AGENT_UNMAPPED_FIELDS = [
  'description',
  'model',
  'tools',
  'color',
  'permission_mode',
  'max_turns',
  'temperature',
  'mode',
  'memory',
] as const;

function generateAgentsPlugin(agents: readonly Agent[]): string {
  const lines = [
    '// AUTO-GENERATED by agent-forge; do not edit by hand.',
    '// Source of truth: ./agent-forge-agents.yaml',
    '',
    'export default function (amp) {',
  ];
  for (const agent of agents) {
    lines.push('  amp.createAgent({');
    lines.push(`    name: ${JSON.stringify(agent.name)},`);
    lines.push(`    prompt: ${JSON.stringify(agent.body)},`);
    lines.push('  });');
  }
  lines.push('}');
  return lines.join('\n');
}

export async function writeAmpAgents(
  ir: IR,
  scope: Scope,
  cwd: string,
  opts: WriteOpts = {},
): Promise<WriteReport> {
  const agents = ir.agents ?? [];
  if (agents.length === 0) return { written: [], skipped: [], warnings: [] };

  const warnings: string[] = [];
  for (const agent of agents) {
    for (const field of AGENT_UNMAPPED_FIELDS) {
      if ((agent as unknown as Record<string, unknown>)[field] !== undefined) {
        warnings.push(
          `agents/${agent.name}: '${field}' has no amp.createAgent() field mapping (dropped) [AM2][AM9]`,
        );
      }
    }
  }

  const p = paths(scope, cwd);
  if (!opts.dryRun) {
    await mkdir(p.pluginsDir, { recursive: true });
    await writeFile(p.agentsPluginFile, generateAgentsPlugin(agents), 'utf8');
    await writeFile(
      p.agentsManifestFile,
      dump({ agents }, { lineWidth: 100, noRefs: true }),
      'utf8',
    );
  }
  return {
    written: [p.agentsPluginFile, p.agentsManifestFile],
    skipped: [],
    warnings,
  };
}

export async function readAmpAgents(
  scope: Scope,
  cwd: string,
): Promise<Agent[] | undefined> {
  const p = paths(scope, cwd);
  if (!existsSync(p.agentsManifestFile)) return undefined;
  const text = await readFile(p.agentsManifestFile, 'utf8');
  const parsed = (load(text) ?? {}) as { agents?: Agent[] };
  return parsed.agents?.length ? parsed.agents : undefined;
}

// ---- commands --------------------------------------------------------------

/** IR command fields `amp.registerCommand()` has no documented parameter
 * for — only `name` + the prompt body are mapped [AM2]. */
const COMMAND_UNMAPPED_FIELDS = [
  'description',
  'argument_hint',
  'model',
  'allowed_tools',
] as const;

function generateCommandsPlugin(commands: readonly Command[]): string {
  const lines = [
    '// AUTO-GENERATED by agent-forge; do not edit by hand.',
    '// Source of truth: ./agent-forge-commands.yaml',
    '',
    'export default function (amp) {',
  ];
  for (const command of commands) {
    lines.push('  amp.registerCommand({');
    lines.push(`    name: ${JSON.stringify(command.name)},`);
    lines.push(`    prompt: ${JSON.stringify(command.body)},`);
    lines.push('  });');
  }
  lines.push('}');
  return lines.join('\n');
}

export async function writeAmpCommands(
  ir: IR,
  scope: Scope,
  cwd: string,
  opts: WriteOpts = {},
): Promise<WriteReport> {
  const commands = ir.commands ?? [];
  if (commands.length === 0) return { written: [], skipped: [], warnings: [] };

  const warnings: string[] = [];
  for (const command of commands) {
    for (const field of COMMAND_UNMAPPED_FIELDS) {
      if (
        (command as unknown as Record<string, unknown>)[field] !== undefined
      ) {
        warnings.push(
          `commands/${command.name}: '${field}' has no amp.registerCommand() field mapping (dropped) [AM2]`,
        );
      }
    }
  }

  const p = paths(scope, cwd);
  if (!opts.dryRun) {
    await mkdir(p.pluginsDir, { recursive: true });
    await writeFile(
      p.commandsPluginFile,
      generateCommandsPlugin(commands),
      'utf8',
    );
    await writeFile(
      p.commandsManifestFile,
      dump({ commands }, { lineWidth: 100, noRefs: true }),
      'utf8',
    );
  }
  return {
    written: [p.commandsPluginFile, p.commandsManifestFile],
    skipped: [],
    warnings,
  };
}

export async function readAmpCommands(
  scope: Scope,
  cwd: string,
): Promise<Command[] | undefined> {
  const p = paths(scope, cwd);
  if (!existsSync(p.commandsManifestFile)) return undefined;
  const text = await readFile(p.commandsManifestFile, 'utf8');
  const parsed = (load(text) ?? {}) as { commands?: Command[] };
  return parsed.commands?.length ? parsed.commands : undefined;
}

// ---- hooks -------------------------------------------------------------

function generateHooksPlugin(hooks: readonly Hook[]): string {
  const lines = [
    '// AUTO-GENERATED by agent-forge; do not edit by hand.',
    '// Source of truth: ./agent-forge-hooks.yaml',
    "import { spawnSync } from 'node:child_process';",
    '',
    'function runHook(command, payload) {',
    "  spawnSync('sh', ['-c', command], {",
    '    input: JSON.stringify(payload),',
    "    stdio: ['pipe', 'inherit', 'inherit'],",
    '  });',
    '}',
    '',
    'export default function (amp) {',
  ];

  const byEvent = new Map<string, Hook[]>();
  for (const hook of hooks) {
    for (const e of hook.events) {
      const native = canonicalToAmp[e];
      if (!native) continue;
      const list = byEvent.get(native) ?? [];
      list.push(hook);
      byEvent.set(native, list);
    }
  }

  for (const [nativeEvent, list] of byEvent) {
    lines.push(`  amp.on(${JSON.stringify(nativeEvent)}, (payload) => {`);
    for (const hook of list) {
      const meta = JSON.stringify({
        id: hook.id,
        canonicalEvent: hook.events[0],
      });
      lines.push(
        `    runHook(${JSON.stringify(hook.command)}, { ...payload, _agentForge: ${meta} });`,
      );
    }
    lines.push('  });');
  }

  lines.push('}');
  return lines.join('\n');
}

export async function writeAmpHooks(
  ir: IR,
  scope: Scope,
  cwd: string,
  opts: WriteOpts = {},
): Promise<WriteReport> {
  const hooks = ir.hooks ?? [];
  if (hooks.length === 0) return { written: [], skipped: [], warnings: [] };

  const warnings: string[] = [];
  const skipped: { path: string; reason: string }[] = [];
  const compatible: Hook[] = [];
  for (const hook of hooks) {
    const unmapped = hook.events.filter((e) => !canonicalToAmp[e]);
    if (unmapped.length === hook.events.length) {
      warnings.push(
        `hook '${hook.id ?? '?'}': no amp.on() equivalent for events ${unmapped.join(',')} [AM2][AM7]`,
      );
      skipped.push({
        path: `hooks/${hook.id ?? '?'}.yaml`,
        reason: `no amp mapping for events: ${unmapped.join(',')}`,
      });
      continue;
    }
    if (unmapped.length > 0) {
      warnings.push(
        `hook '${hook.id ?? '?'}': partial mapping; events ${unmapped.join(',')} dropped [AM2][AM7]`,
      );
    }
    if (hook.matcher) {
      warnings.push(
        `hook '${hook.id ?? '?'}': matcher '${hook.matcher}' has no verified amp.on() payload-matching field (dropped) [AM2]`,
      );
    }
    compatible.push(hook);
  }

  const p = paths(scope, cwd);
  if (compatible.length > 0) {
    if (!opts.dryRun) {
      await mkdir(p.pluginsDir, { recursive: true });
      await writeFile(
        p.hooksPluginFile,
        generateHooksPlugin(compatible),
        'utf8',
      );
      await writeFile(
        p.hooksManifestFile,
        dump({ hooks: compatible }, { lineWidth: 100, noRefs: true }),
        'utf8',
      );
    }
    return {
      written: [p.hooksPluginFile, p.hooksManifestFile],
      skipped,
      warnings,
    };
  }
  return { written: [], skipped, warnings };
}

export async function readAmpHooks(
  scope: Scope,
  cwd: string,
): Promise<Hook[] | undefined> {
  const p = paths(scope, cwd);
  if (!existsSync(p.hooksManifestFile)) return undefined;
  const text = await readFile(p.hooksManifestFile, 'utf8');
  const parsed = (load(text) ?? {}) as { hooks?: Hook[] };
  return parsed.hooks?.length ? parsed.hooks : undefined;
}
