// project-human ≜ the harness-AGNOSTIC half of boundary-projection: render a
// canonical cell to its human-view. The model law
//
//   project-human(c) = ⟨ σ_human*(k) : k ∈ concepts(c) ⟩
//
// A human-view is COMPOSED from the human-signs of the cell's concepts — never
// authored at the boundary. `projectHumanDimension` realizes it for the DIMENSION unit:
// its concepts are the dimension itself (σ_human* = the optional `DimensionDoc.gloss`) and
// its value cells (σ_human* = each value's `slug ≜ definiens`). The output is a
// PURE DETERMINISTIC function of `(dimension, values, doc, manifest)` — sort is by slug,
// meta is read from the given manifest, no clock/host/IO — so a committed README that diverges
// from re-projection is a hand-edit (the falsifier), catchable by a byte diff.

import type { DimensionManifest } from '@cratylus/schema';

/**
 * The optional dimension-level human gloss — `σ_human*` of the DIMENSION concept itself,
 * composed by `projectHumanDimension` above the value list. Source-owned; when a
 * projected dimension has no `DimensionDoc`, a default genus line from the given
 * catalog's meta stands in its place.
 */
export interface DimensionDoc {
  readonly dimension: string;
  /** One-paragraph human gloss of what this dimension is (markdown, no trailing nl). */
  readonly gloss: string;
}

/** `audience-adaptation` → `Audience-Adaptation`, `output-format` → `Output-Format`. */
function dimensionTitle(dimension: string): string {
  return dimension
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('-');
}

/** Lexicographic order — the deterministic value ordering of a human-view. */
function byBody(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * `project-human` for a dimension: compose its value cells into the canonical human
 * README. PURE and DETERMINISTIC in `(dimension, values, doc, manifest)` — the value
 * list is slug-sorted, the genus line is read from the catalog, and nothing else
 * enters. The closed shape:
 *
 *   # <dimension>
 *
 *   > **Dimension — <AXIS> · <Title>.** <doc.gloss | default genus line>
 *
 *   ## Values
 *
 *   - **`<slug>`** ≜ <definiens>
 *   …
 *
 *   ---
 *
 *   _<generated-by footer>_
 *
 * A committed `dimensions/<dimension>/README.md` is projection-owned iff it equals this
 * output byte-for-byte; any hand-edit diverges and the boundary gate fails.
 */
export function projectHumanDimension(
  dimension: string,
  values: readonly string[],
  doc: DimensionDoc | undefined,
  manifest: DimensionManifest,
): string {
  const meta = manifest[dimension];
  // A catalog lookup is TOTAL by construction — the dimension being projected is
  // one of the catalog's own. Refuse rather than render `undefined` into a genus
  // line: a README that reads as authored is the one failure a byte diff cannot
  // distinguish from a hand-edit.
  if (!meta) {
    throw new Error(
      `project-human: '${dimension}' is not a dimension of the given catalog`,
    );
  }
  const title = dimensionTitle(dimension);
  const sorted = [...values].sort(byBody);

  const lines: string[] = [`# ${dimension}`, ''];
  lines.push(
    doc
      ? `> **Dimension — ${meta.axis} · ${title}.** ${doc.gloss}`
      : `> **Dimension — ${meta.axis} · ${title}** — a ${meta.kind} ${meta.arity} dimension.`,
    '',
  );
  lines.push('## Values', '');
  for (const body of sorted) {
    lines.push(`- ${body}`);
  }
  lines.push(
    '',
    '---',
    '',
    `_This file is the human projection of \`dimensions/${dimension}/\` — generated by \`project-human\` from the dimension’s canonical semantics (${meta.kind} ${meta.arity} value-catalog). Edit the \`.ts\` value cells and regenerate; do not hand-edit._`,
  );
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}
