// ─────────────────────────────────────────────────────────────────────────────
// THE INSTALL VERB — the artifact that AUTHORS this host's binding of the bin key.
//
// WHAT IT REPAIRS. Until 2026-08-05 the run-time bin reached this host's PATH
// through a `pnpm link --global`, i.e. a relative symlink into the checkout that
// NO ARTIFACT IN THIS REPOSITORY AUTHORED. Renaming the workspace directory
// stranded it; every deployed skill shim then died inside node's module loader
// with MODULE_NOT_FOUND, `/wake` could not run, and the repository stayed green
// and clean throughout — because nothing in the repository had ever claimed the
// binding, nothing in the repository could notice it break.
//
// The hand-authored 86-byte recovery file that got the host running again was the
// same defect wearing a repair's clothes: still unauthored, still absolute, still
// silent when stale. This module is the authored replacement.
//
// WHY IT LIVES IN `invoke` AND NOT IN `forge deploy`. The shard proposed deploy —
// it already knows the host root. Two ARCHITECTURE properties say otherwise:
//
//   * `invoke` OWNS THE BIN KEY. ARCHITECTURE: "It owns the `bin` key — the one
//     copy of the bin name no TypeScript can compute." The install verb authors
//     the HOST-side half of exactly that binding: the pair ⟨bin name, executable
//     path⟩. Put it in forge and forge holds a second, independent copy of a
//     binding whose whole point is having one home — the very failure mode
//     `runtime/src/bin-name.ts` was built to end.
//
//   * FORGE WOULD HAVE TO REACH `invoke`. To author a link, the installer must
//     know where the run-time entry IS. Only the package that ships it does.
//     A `forge → invoke` edge drags `invoke → memory` behind it, re-coupling the
//     build DAG to the run-time DAG at distribution — the precise re-coupling
//     ARCHITECTURE §"Two bins, and the last column is why" says the split exists
//     to prevent. Forge's half of this repair needs no such edge: it probes a
//     name on PATH by executing it (`deploy/bundle.ts`), and knows nothing else.
//
// So the seam is: `invoke` AUTHORS the binding, `forge` REFUSES a deploy that
// would place shims against a binding that does not execute. Neither imports the
// other.
//
// WHAT IT CANNOT DO, STATED PLAINLY. The shim carries an ABSOLUTE path into a
// checkout, and no honest alternative exists: after the directory moves, nothing
// on this host knows where it went, so no recorded form of the path can find it.
// The property this module actually delivers is therefore the second half of the
// constraint — it MUST FAIL LOUDLY WHEN IT HAS NOT SURVIVED. The authored shim
// checks its own entry before exec'ing and reports in CAPABILITY terms, naming
// the one command that re-authors it. Re-running the verb from the moved checkout
// is the whole recovery, and it is a documented command rather than archaeology.
// ─────────────────────────────────────────────────────────────────────────────

import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { delimiter, extname, isAbsolute, join, resolve } from 'node:path';
import { RUNTIME_BIN } from '@cratylus/runtime/bin-name';

/** The line every authored shim carries, and the ONLY licence this verb has to
 *  overwrite a file it finds in place. A destination without it belongs to
 *  somebody else and is refused rather than clobbered. */
export const SHIM_MARKER = `GENERATED by \`${RUNTIME_BIN} install\` (cratylus)`;

/** Quote a path for `/bin/sh` single-quoted context, escaping embedded quotes. */
function sq(s: string): string {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

/**
 * The authored host shim, as text. A REAL FILE, deliberately — not a symlink.
 *
 * Symlinking a package-manager bin shim does not work and cost a recovery to
 * learn: such a shim resolves its target relative to its own `basedir`, so a
 * symlink re-anchors that basedir and the shim points at a path that does not
 * exist. `#!/bin/sh` + `exec node <abs> "$@"` is the form that works.
 *
 * The guard clause above the `exec` is the part that matters. Without it a stale
 * entry surfaces as a node module-loader stack from a file no one remembers
 * exists; with it, the failure is a capability-level sentence naming its own
 * repair. Pure `f(entry, bin)` — no I/O, so it is inspectable via `--print`.
 */
export function shimContent(entry: string, bin: string = RUNTIME_BIN): string {
  return `#!/bin/sh
# ${bin} — the host binding of the run-time bin.
# ${SHIM_MARKER}
# Do NOT hand-edit: re-run the install verb to re-author it.
#
# This file carries an ABSOLUTE path into a checkout. That is not an oversight —
# once the checkout moves, nothing on this host knows where it went, so no
# recorded form of the path could find it. What this file guarantees instead is
# that a stale binding FAILS LEGIBLY, in capability terms, naming its repair,
# rather than dying inside node's module loader the way the unauthored
# \`pnpm link --global\` symlink did on 2026-08-05.
CRATYLUS_RUN_ENTRY=${sq(entry)}

if [ ! -f "$CRATYLUS_RUN_ENTRY" ]; then
  cat >&2 <<EOF
${bin}: UNAVAILABLE — the run-time capability is not installed on this host.

  this command   $0
  its entry      $CRATYLUS_RUN_ENTRY
  status         that file does not exist

The checkout moved, was deleted, or its dist/ was cleaned. Nothing on this host
records where it went, so re-author this binding from wherever the checkout is
now:

  node <checkout>/packages/cli/dist/bin.js install

Until then every deployed skill shim that spawns ${bin} is inert.
EOF
  exit 127
fi

if ! command -v node >/dev/null 2>&1; then
  echo "${bin}: UNAVAILABLE — 'node' is not on PATH, and the run-time entry needs it." >&2
  exit 127
fi

exec node "$CRATYLUS_RUN_ENTRY" "$@"
`;
}

export interface InstallOpts {
  /** Absolute path to the run-time entry the shim will exec — normally the
   *  executing `dist/bin.js`, passed in by the bin so this module never has to
   *  guess its own location through a bundler. */
  readonly entry: string;
  /** Explicit destination bin dir; else resolved by {@link resolveBinDir}. */
  readonly dir?: string | null;
  readonly env?: NodeJS.ProcessEnv;
  readonly home?: string;
  /** Overwrite a destination file this verb did not author. */
  readonly force?: boolean;
  /** Skip the post-write `--version` self-probe (used only to keep the verb
   *  usable on a host whose node is being replaced). */
  readonly noVerify?: boolean;
  readonly log?: (line: string) => void;
  readonly warn?: (line: string) => void;
}

export interface InstallResult {
  /** 0 authored and verified · 2 refused (nothing written, or written-and-broken). */
  readonly rc: 0 | 2;
  readonly path: string | null;
  readonly entry: string;
  readonly dir: string | null;
  /** Whether the destination dir is on this host's PATH. A warning, not a
   *  refusal: the file is correct either way. */
  readonly onPath: boolean;
  readonly reason: string | null;
}

/**
 * Where the binding goes, most explicit first:
 *   1. `--dir`                  — the operator said so
 *   2. `$CRATYLUS_BIN_DIR`      — this tool's own override
 *   3. `$PNPM_HOME`             — pnpm's global bin dir, already on PATH where
 *                                 pnpm installed it; this is where the stranded
 *                                 link lived, so re-authoring lands in place
 *   4. `~/.local/bin`           — the conventional user bin dir
 */
export function resolveBinDir(
  explicit: string | null | undefined,
  env: NodeJS.ProcessEnv,
  home: string,
): string {
  if (explicit) return resolve(explicit);
  if (env.CRATYLUS_BIN_DIR) return resolve(env.CRATYLUS_BIN_DIR);
  if (env.PNPM_HOME) return resolve(env.PNPM_HOME);
  return join(home, '.local', 'bin');
}

/** Is `dir` an entry of `$PATH`? Diagnostic only. */
export function onPath(dir: string, env: NodeJS.ProcessEnv): boolean {
  const target = resolve(dir);
  return (env.PATH ?? '')
    .split(delimiter)
    .filter(Boolean)
    .some((p) => resolve(p) === target);
}

/**
 * Author the host binding, then PROVE IT RUNS.
 *
 * The self-probe is the whole lesson of the outage restated at install time:
 * `which` was satisfied by the stranded shim the entire time it was broken, so
 * presence is not resolvability. This verb executes what it just wrote with
 * `--version` and refuses if that does not come back — an installer that reports
 * success over a shim that cannot run is the same defect one layer earlier.
 */
export function installRuntimeBin(opts: InstallOpts): InstallResult {
  const log = opts.log ?? (() => {});
  const warn = opts.warn ?? (() => {});
  const env = opts.env ?? process.env;
  const home = opts.home ?? homedir();
  const entry = resolve(opts.entry);

  const refuse = (
    reason: string,
    lines: string[],
    dir: string | null = null,
    path: string | null = null,
  ): InstallResult => {
    warn(`${RUNTIME_BIN} install: REFUSED — ${reason}`);
    for (const l of lines) warn(l);
    return { rc: 2, path, entry, dir, onPath: false, reason };
  };

  if (!existsSync(entry)) {
    return refuse('the run-time entry does not exist', [
      `  entry   ${entry}`,
      '  A binding may only be authored against an entry that is present. Build',
      '  the package first, then re-run this verb from the built bin.',
    ]);
  }
  // Guard the tsx/dev-loop foot-gun: a shim pointing at TypeScript would author a
  // binding that fails on every host invocation, which is exactly the class of
  // artifact this verb exists to stop shipping.
  if (!['.js', '.mjs', '.cjs'].includes(extname(entry))) {
    return refuse('the run-time entry is not a node-executable file', [
      `  entry   ${entry}`,
      '  The shim execs `node <entry>`, so the entry must be built JavaScript.',
      '  Build the package and run the install verb from `dist/bin.js`.',
    ]);
  }

  const dir = resolveBinDir(opts.dir, env, home);
  if (!isAbsolute(dir)) {
    return refuse('the destination bin dir is not absolute', [
      `  dir     ${dir}`,
    ]);
  }
  const dest = join(dir, RUNTIME_BIN);

  // Never clobber a file this verb did not author. A foreign binary sitting on
  // the bin name is an occupancy conflict the operator must settle, not something
  // to silently replace.
  if (existsSync(dest) && !opts.force) {
    const prior = safeRead(dest);
    if (prior !== null && !prior.includes(SHIM_MARKER)) {
      return refuse(
        `${dest} already exists and was not authored by this verb`,
        [
          '  Something else occupies this bin name here. Inspect it, then re-run',
          '  with --force if replacing it is what you mean.',
        ],
        dir,
        dest,
      );
    }
  }

  mkdirSync(dir, { recursive: true });
  writeFileSync(dest, shimContent(entry), 'utf-8');
  chmodSync(dest, 0o755);

  const dirOnPath = onPath(dir, env);
  log(`${RUNTIME_BIN} install: authored ${dest}`);
  log(`  entry   ${entry}`);

  if (!opts.noVerify) {
    const probe = spawnSync(dest, ['--version'], {
      encoding: 'utf-8',
      timeout: 20_000,
    });
    const version = (probe.stdout ?? '').trim().split('\n')[0] ?? '';
    if (probe.error || probe.status !== 0 || version === '') {
      return refuse(
        'the authored binding does not execute',
        [
          `  probe   ${dest} --version`,
          `  result  ${probe.error ? String(probe.error.message) : `exited ${String(probe.status)}`}`,
          ...salientStderr(probe.stderr).map((l) => `  stderr  ${l}`),
          '  The file was written, but it cannot run — so the binding is NOT in',
          '  place. Presence is not resolvability; this verb refuses to report a',
          '  success `which` would have agreed with.',
        ],
        dir,
        dest,
      );
    }
    log(`  probe   ${RUNTIME_BIN} --version -> ${version}`);
  }

  if (!dirOnPath) {
    warn(`${RUNTIME_BIN} install: WARN ${dir} is not on this host's PATH.`);
    warn(
      `  The binding is authored and runs, but nothing will find it by name. Add:  export PATH="${dir}:$PATH"`,
    );
  }

  return { rc: 0, path: dest, entry, dir, onPath: dirOnPath, reason: null };
}

function safeRead(p: string): string | null {
  try {
    if (!statSync(p).isFile()) return null;
    return readFileSync(p, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Reduce a failing process's stderr to the ONE line worth quoting.
 *
 * "First line" is not enough: a stranded shim's stderr OPENS with
 * `node:internal/modules/cjs/loader:1573`, so quoting it reproduces the loader
 * frame this whole repair exists to replace. Prefer the error sentence — here
 * that is `Error: Cannot find module '<the path that is gone>'`, which names the
 * strand itself.
 *
 * Forge's deploy gate carries an identical reducer, and the duplication is
 * deliberate rather than an oversight: `invoke` and `forge` are the run-time and
 * build-time DAGs, and ARCHITECTURE keeps them from reaching across. Sharing
 * eleven lines of string handling is not worth the edge that would carry it.
 */
function salientStderr(s: string | null | undefined): string[] {
  const lines = (s ?? '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  const isNoise = (l: string): boolean =>
    l.startsWith('node:') ||
    l.startsWith('at ') ||
    l.startsWith('throw ') ||
    /^\^+$/.test(l) ||
    /^[\w./-]+:\d+(:\d+)?$/.test(l);
  const pick =
    lines.find((l) => /^[A-Za-z_$][\w$]*Error\b/.test(l) && !isNoise(l)) ??
    lines.find((l) => !isNoise(l));
  return pick ? [pick.length > 200 ? `${pick.slice(0, 197)}...` : pick] : [];
}

const USAGE = `${RUNTIME_BIN} install — author this host's binding of the run-time bin.

  ${RUNTIME_BIN} install [--dir <bindir>] [--entry <path>] [--force] [--print]

Writes an executable ${RUNTIME_BIN} shim that execs the run-time entry, then proves
it runs with --version. Re-run it after moving or re-cloning the checkout: that is
the whole recovery.

  --dir <bindir>   destination (default: $CRATYLUS_BIN_DIR, else $PNPM_HOME,
                   else ~/.local/bin)
  --entry <path>   the run-time entry to bind (default: this executing bin)
  --force          replace a file at the destination this verb did not author
  --print          write the shim to stdout and install nothing
  --no-verify      skip the post-write --version probe
`;

export interface RunInstallCtx {
  /** The executing run-time entry, supplied by the bin. */
  readonly entry: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly home?: string;
  readonly log?: (line: string) => void;
  readonly warn?: (line: string) => void;
}

/** Parse the verb's flags and run it. Returns the process exit code. */
export function runInstall(
  argv: readonly string[],
  ctx: RunInstallCtx,
): number {
  const log = ctx.log ?? (() => {});
  const warn = ctx.warn ?? (() => {});
  let dir: string | null = null;
  let entry = ctx.entry;
  let force = false;
  let print = false;
  let noVerify = false;

  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--help' || a === '-h') {
      log(USAGE);
      return 0;
    }
    if (a === '--force') {
      force = true;
      continue;
    }
    if (a === '--print') {
      print = true;
      continue;
    }
    if (a === '--no-verify') {
      noVerify = true;
      continue;
    }
    if (a === '--dir' || a === '--entry') {
      const v = argv[i + 1];
      if (v === undefined || v.startsWith('-')) {
        warn(`${RUNTIME_BIN} install: ${a} requires a value`);
        return 2;
      }
      if (a === '--dir') {
        dir = v;
      } else {
        entry = v;
      }
      i += 1;
      continue;
    }
    // An unknown option must FAIL BY NAME, never be absorbed. This verb's whole
    // job is to leave a host in a state it can trust; silently ignoring a
    // misspelled `--dir` would author the binding somewhere else and report
    // success.
    warn(`${RUNTIME_BIN} install: unknown option '${String(a)}'`);
    warn(USAGE);
    return 2;
  }

  if (print) {
    log(shimContent(resolve(entry)));
    return 0;
  }

  return installRuntimeBin({
    entry,
    dir,
    force,
    noVerify,
    env: ctx.env,
    home: ctx.home,
    log,
    warn,
  }).rc;
}
