// project-human gate (E2): `projectHumanDimension` is a PURE DETERMINISTIC function of
// `(dimension, values, doc)`. Proven here over a synthetic fixture — determinism
// (idempotent across runs + input-order-independent via slug sort), the closed
// shape, and the source-only footer. The CORPUS witness (a committed dimension README
// that equals its re-projection byte-for-byte) lives in canon's
// `test/projection-boundary.test.ts`; this proves the function it depends on.

import { describe, expect, it } from 'vitest';
import {
  type DimensionDoc,
  projectHumanDimension,
} from '../../src/project/project-human.js';
import { FIXTURE_ANATOMY } from '../fixture-anatomy.js';

// `heuristics` is a Constitution/coined/set dimension — a stable fixture for the shape.
// Each value IS the SOUL body `<slug> ≜ <definiens>` — no `{dimension,slug,definiens}`
// wrapper (that shape is retired; the string carries the body).
const values: readonly string[] = [
  'take-the-best ≜ decide on the one best cue.',
  'anchoring ≜ anchor, adjust insufficiently.',
  'recognition ≜ choose the recognized option.',
];

describe('projectHumanDimension — pure deterministic human-view', () => {
  it('is idempotent (same bytes across repeated projection)', () => {
    const a = projectHumanDimension(
      'heuristics',
      values,
      undefined,
      FIXTURE_ANATOMY,
    );
    const b = projectHumanDimension(
      'heuristics',
      values,
      undefined,
      FIXTURE_ANATOMY,
    );
    expect(a).toBe(b);
  });

  it('is input-order-independent (slug-sorted)', () => {
    const forward = projectHumanDimension(
      'heuristics',
      values,
      undefined,
      FIXTURE_ANATOMY,
    );
    const shuffled = projectHumanDimension(
      'heuristics',
      [values[2] as string, values[0] as string, values[1] as string],
      undefined,
      FIXTURE_ANATOMY,
    );
    expect(shuffled).toBe(forward);
    // The value order in the output is body-lexicographic, not source order.
    const md = forward;
    const iAnchor = md.indexOf('anchoring ≜');
    const iRecog = md.indexOf('recognition ≜');
    const iTake = md.indexOf('take-the-best ≜');
    expect(iAnchor).toBeLessThan(iRecog);
    expect(iRecog).toBeLessThan(iTake);
  });

  it('emits the closed shape: H1, genus quote, Values, footer', () => {
    const md = projectHumanDimension(
      'heuristics',
      values,
      undefined,
      FIXTURE_ANATOMY,
    );
    expect(md.startsWith('# heuristics\n')).toBe(true);
    expect(md).toContain(
      '> **Dimension — Constitution · Heuristics** — a coined set dimension.',
    );
    expect(md).toContain('## Values');
    expect(md).toContain('- anchoring ≜ anchor, adjust insufficiently.');
    expect(md).toContain('generated by `project-human`');
    expect(md).toContain('do not hand-edit._');
    expect(md.endsWith('\n')).toBe(true);
  });

  it('an DimensionDoc gloss replaces the default genus line', () => {
    const doc: DimensionDoc = {
      dimension: 'heuristics',
      gloss:
        'the standing move-biases that incline an agent toward some choices.',
    };
    const md = projectHumanDimension(
      'heuristics',
      values,
      doc,
      FIXTURE_ANATOMY,
    );
    expect(md).toContain(
      '> **Dimension — Constitution · Heuristics.** the standing move-biases that incline an agent toward some choices.',
    );
    expect(md).not.toContain('— a coined set dimension.');
  });
});
