// The claude projection of a dimension value fragment: render a typed module back to
// its canonical cell-body markdown form.
//
// The skill round-trip machinery (`SkillModule` / `skillToMarkdown`) was retired in
// the forge-anatomy de-braid: a skill no longer stores a verbatim `body`, its sole
// σ* payload is the forge `Skill.formalBlock` and its SKILL.md is generated by the
// forge claude/codex adapter (`skillToClaudeMd`), never round-tripped from a stored
// body. Only the fragment wrap survives (its byte-anchor is the value string
// itself).

import { bodyOf } from '@cratylus/schema';
import type { Dimension, Value } from '../anatomy.js';

/**
 * Render a dimension value to its canonical cell body: `\n\n<body>\n`.
 *
 * Takes a VALUE, not a string. A value's content IS the body ⟨α, residue⟩ when it
 * is bare, but a value may now carry its own enforcement, and then the body is one
 * face of an object. `bodyOf` reaches it either way; interpolating the value
 * directly would render `[object Object]` into the cell.
 *
 * Only the DECLARATION is projected here. Substrate, events and the mechanism are
 * where the rule binds, not what it says — they are realized by the adapter into
 * the governed agent's own front-matter, never into the cell body.
 */
export function fragmentToMarkdown(value: Value<Dimension>): string {
  return `\n\n${bodyOf(value)}\n`;
}
